
import java.awt.CardLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asyifanamirah
 */
public class PilihGambarComboBox extends javax.swing.JFrame {

    private Object pilihan;

    /**
     * Creates new form PilihGambarComboBox
     */
    public PilihGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCardLayout = new javax.swing.JPanel();
        textGambar = new javax.swing.JLabel();
        ComboBox = new javax.swing.JComboBox<>();
        image = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textGambar.setText("Pilih Gambar :");
        pCardLayout.add(textGambar);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Gambar", "Kupu-Kupu", "Kucing", "Kelinci" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });
        pCardLayout.add(ComboBox);

        getContentPane().add(pCardLayout, java.awt.BorderLayout.PAGE_START);

        image.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/asyifanamirah/Desktop/kupu-kupu.JPG")); // NOI18N
        image.add(jLabel1, "card2");

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/asyifanamirah/Desktop/kucing.JPG")); // NOI18N
        image.add(jLabel2, "card3");

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/asyifanamirah/Desktop/kelinci.JPG")); // NOI18N
        image.add(jLabel3, "card4");

        getContentPane().add(image, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // kode untuk menjalankan combobox
        CardLayout cardLayout = (CardLayout) image.getLayout();
        String selectedOption = (String) ComboBox.getSelectedItem();
if (!"Pilih Disini".equals(selectedOption)) { switch (selectedOption) {
case "Kupu-Kupu":
    cardLayout.show(image, "0");
break;
case "Kucing": 
    cardLayout.show(image, "1"); 
break;
case "Kelinci": 
    cardLayout.show(image, "2");
break;
    
        
} }
    }//GEN-LAST:event_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JPanel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pCardLayout;
    private javax.swing.JLabel textGambar;
    // End of variables declaration//GEN-END:variables

    
}
